name: Terpaling Workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Build and Deploy
        id: swa
        uses: azure/static-web-apps-deploy@latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "" # App source code path
          output_location: "out" # Built app content directory - optional
        env: # Add environment variables here
          is_static_export: true       
        ###### End of Repository/Build Configurations ######